name: One-Click VPS (tmate)
on: [workflow_dispatch]

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # up to 6 hours
    steps:
      - name: Prep machine
        run: |
          sudo apt-get update
          sudo apt-get install -y htop curl git

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false   # ✅ allows web terminal without GitHub SSH keys

      - name: Keep alive
        run: sleep 21600
