name: GitHub VPS
on: [workflow_dispatch]

jobs:
  vps:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server wget unzip jq
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:password123" | sudo chpasswd

      - name: Install ngrok
        run: |
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip -o ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin/ngrok

      - name: Start ngrok tunnel
        env:
          NGROK_AUTH: ${{ secrets.NGROK_AUTH }}
        run: |
          ngrok authtoken $NGROK_AUTH
          nohup ngrok tcp 22 --log=stdout > ngrok.log 2>&1 &
          
          # Wait until tunnel is ready
          for i in {1..15}; do
            HOSTPORT=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            if [[ "$HOSTPORT" == tcp* ]]; then
              break
            fi
            sleep 2
          done
          
          HOST=$(echo $HOSTPORT | cut -d':' -f2 | sed 's#^//##')
          PORT=$(echo $HOSTPORT | cut -d':' -f3)

          echo "SSH command: ssh root@$HOST -p $PORT" >> $GITHUB_STEP_SUMMARY
          echo "Password: password123" >> $GITHUB_STEP_SUMMARY

          echo "====================================="
          echo "SSH Host: $HOST"
          echo "SSH Port: $PORT"
          echo "User: root"
          echo "Password: password123"
          echo "====================================="

      - name: Keep VPS Alive
        run: sleep 21600
